<a href="https://colab.research.google.com/github/NotYeshwanthReddy/empty/blob/master/PythonCheatSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python

### Help

In [0]:
class Test:
  """Demo test class  """
  def __init__():
    s = 10
  def function(arg1:str, arg2:int,arg3:list) -> str:
    ''' Takes in 3 args
    returns results
    '''
    return arg1

help( function)
? function()

# TODO: Add condition for when val is None

Help on function function in module __main__:

function(arg1:str, arg2:int, arg3:list) -> str
    Takes in 3 args
    returns results



In [0]:
print(Test.__doc__)
print(Test.__init__)
print(help(Test))
print(dir(Test))

Demo test class  
<function Test.__init__ at 0x7f5ad59bbf28>
Help on class Test in module __main__:

class Test(builtins.object)
 |  Demo test class
 |  
 |  Methods defined here:
 |  
 |  __init__()
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  function(arg1:str, arg2:int, arg3:list) -> str
 |      Takes in 3 args
 |      returns results
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

None
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'funct

In [0]:
# ? = jupyter symbol, shows help of a function
? np.shape

# NumPy


In [0]:
# NumPy Reference Resource - Cheat sheet
# https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

import numpy as np

## Delcare array

In [0]:
# a = np.array([(1.2,2,3),
              # (2.3,4,5)], dtype=float)
b = np.array([[1.2,2,3],
              [2.3,4,5]], dtype=float)
c = np.array([[(1.5,2,3),
               (4,5,6)], 
              [(3,2,1), 
               (4,5,6)]], dtype = float)

In [0]:
# print(a, np.shape(a))
print(b, np.shape(b))
print(c, np.shape(c))

[[1.2 2.  3. ]
 [2.3 4.  5. ]] (2, 3)
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] (2, 2, 3)


## Auto create array

In [0]:
np.linspace(0,2,10)
np.random.random((3,4)) # never give one arg. will create a Rank 1 array.
np.full((2,3),7)
np.zeros((3,4))
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

## Array Properties

In [0]:
e = np.empty((7,7))
print(e)
print(np.shape(e))
print(np.size(e))
print(e.shape)
print(e.size)
print(e.dtype)
# print(e.dtype.name)
print(e.astype(int))

[[3.05890349e-316 2.33475203e-131 6.93477243e-310 6.93477243e-310
  1.00417949e-131 6.93477243e-310 6.93477243e-310]
 [1.71893259e+049 6.93477243e-310 6.93477243e-310 3.90368375e-007
  6.93477243e-310 6.93477243e-310 1.30810436e+115]
 [6.93477243e-310 6.93477243e-310 6.20125448e-256 6.93477243e-310
  6.93477243e-310 1.47881230e+142 6.93477243e-310]
 [6.93477243e-310 1.95963641e-212 6.93477243e-310 6.93477243e-310
  2.63815993e-011 6.93477243e-310 6.93477243e-310]
 [2.55416341e-113 6.93477243e-310 6.93477243e-310 4.02937796e+089
  6.93477243e-310 6.93477243e-310 9.72446629e-110]
 [6.93477243e-310 6.93477243e-310 6.65225438e+267 6.93477243e-310
  6.93477243e-310 1.40413554e-282 6.93477243e-310]
 [6.93477243e-310 7.35482915e+265 6.93477243e-310 6.93477243e-310
  1.48146156e+066 6.93477243e-310 6.93477243e-310]]
(7, 7)
49
(7, 7)
49
float64
[[                   0                    0                    0
                     0                    0                    0
                     0

## Save and Load arrays

In [0]:
np.save("array",e)    # saves to npy file
np.savez("arrays", a=b,b=c,c=e)   # saves to npz file

In [0]:
import numpy
data = np.load("arrays.npz")     # load npy or npz files
data['c']

array([[3.05890349e-316, 2.33475203e-131, 6.93477243e-310,
        6.93477243e-310, 1.00417949e-131, 6.93477243e-310,
        6.93477243e-310],
       [1.71893259e+049, 6.93477243e-310, 6.93477243e-310,
        3.90368375e-007, 6.93477243e-310, 6.93477243e-310,
        1.30810436e+115],
       [6.93477243e-310, 6.93477243e-310, 6.20125448e-256,
        6.93477243e-310, 6.93477243e-310, 1.47881230e+142,
        6.93477243e-310],
       [6.93477243e-310, 1.95963641e-212, 6.93477243e-310,
        6.93477243e-310, 2.63815993e-011, 6.93477243e-310,
        6.93477243e-310],
       [2.55416341e-113, 6.93477243e-310, 6.93477243e-310,
        4.02937796e+089, 6.93477243e-310, 6.93477243e-310,
        9.72446629e-110],
       [6.93477243e-310, 6.93477243e-310, 6.65225438e+267,
        6.93477243e-310, 6.93477243e-310, 1.40413554e-282,
        6.93477243e-310],
       [6.93477243e-310, 7.35482915e+265, 6.93477243e-310,
        6.93477243e-310, 1.48146156e+066, 6.93477243e-310,
        6.93477243

## save and load text and csv files
Won't use this much. Pandas is used for reading csv and xls files

In [0]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

## Arithmetic Operations

In [0]:
print("c\n",c,"\n b \n",b,"\n c-b \n",(c-b))
print(np.subtract(c,b))
print(np.add(b,c))
print(np.divide(c,b))
print(np.multiply(c,b)) #Multiplication
print(np.exp(b)) #Exponentiation
print(np.sqrt(b)) #Square root
print(np.sin(b)) #Print sines of an array
print(np.cos(b)) #Element-wise cosine
print(np.log(b))  # Element-wise log

c
 [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] 
 b 
 [[1.2 2.  3. ]
 [2.3 4.  5. ]] 
 c-b 
 [[[ 0.3  0.   0. ]
  [ 1.7  1.   1. ]]

 [[ 1.8  0.  -2. ]
  [ 1.7  1.   1. ]]]
[[[ 0.3  0.   0. ]
  [ 1.7  1.   1. ]]

 [[ 1.8  0.  -2. ]
  [ 1.7  1.   1. ]]]
[[[ 2.7  4.   6. ]
  [ 6.3  9.  11. ]]

 [[ 4.2  4.   4. ]
  [ 6.3  9.  11. ]]]
[[[1.25       1.         1.        ]
  [1.73913043 1.25       1.2       ]]

 [[2.5        1.         0.33333333]
  [1.73913043 1.25       1.2       ]]]
[[[ 1.8  4.   9. ]
  [ 9.2 20.  30. ]]

 [[ 3.6  4.   3. ]
  [ 9.2 20.  30. ]]]
[[  3.32011692   7.3890561   20.08553692]
 [  9.97418245  54.59815003 148.4131591 ]]
[[1.09544512 1.41421356 1.73205081]
 [1.51657509 2.         2.23606798]]
[[ 0.93203909  0.90929743  0.14112001]
 [ 0.74570521 -0.7568025  -0.95892427]]
[[ 0.36235775 -0.41614684 -0.9899925 ]
 [-0.66627602 -0.65364362  0.28366219]]
[[0.18232156 0.69314718 1.09861229]
 [0.83290912 1.38629436 1.60943791]]


## Array wise functios

In [0]:
print(b.sum()) #Array-wise sum
print(b.min()) #Array-wise minimum value
print(b.max(axis=0)) #aximum value of an array row
print(b.cumsum(axis=1)) #Cumulative sum of the elements
print(b.mean()) #Mean
# print(b.median()) #Median
# print(b.corrcoef()) #Correlation coefficient
print(np.std(b))

17.5
1.2
[2.3 4.  5. ]
[[ 1.2  3.2  6.2]
 [ 2.3  6.3 11.3]]
2.9166666666666665
1.2707172078091264


In [0]:
print(b.sum(axis=1)) #Array-wise operation
print(b.sum(axis=0)) #Array-wise operation

[ 6.2 11.3]
[3.5 6.  8. ]


In [0]:
x = b.view() # copies the id of b to x. changing x will change b
x = np.copy(b) # copies the whole data of b to x.



In [0]:
x = np.copy(b)

In [0]:
x

array([[111. ,   2. ,   3. ],
       [  2.3,   7. ,  10. ]])

In [0]:
b

array([[ 1.2,  2. ,  3. ],
       [ 2.3,  7. , 10. ]])

In [0]:
x[0,0]=111

## Subsetting, Slicing, Indexing

In [0]:
print(b[1])
print(b[1,0])

[ 2.3  7.  10. ]
2.3


In [0]:
print(b[:1])
print(b[:1,1])
print(c[1,...]) # same as c[1,:,:]

[[1.2 2.  3. ]]
[2.]
[[3. 2. 1.]
 [4. 5. 6.]]


In [0]:
c[c<3] # output an array of elements less than the given value

array([1.5, 2. , 2. , 1. ])

## Array Manipulation

In [0]:
i = np.transpose(b)
print(i)
print(b.ravel())
print(b.reshape(3,-2))
np.vstack((c,b))

[[ 1.2  2.3]
 [ 2.   7. ]
 [ 3.  10. ]]
[ 1.2  2.   3.   2.3  7.  10. ]
[[ 1.2  2. ]
 [ 3.   2.3]
 [ 7.  10. ]]


---

# Pandas

In [0]:
# https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
data = pd.read_csv("gdrive/My Drive/Bin/datasets/fifa19/fifa19.csv")

In [0]:
data.head()

Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

In [0]:
# data.shape[0]
data['Nationality'].value_counts()

England          1662
Germany          1198
Spain            1072
Argentina         937
France            914
                 ... 
Mauritius           1
Lebanon             1
Malta               1
New Caledonia       1
Guam                1
Name: Nationality, Length: 164, dtype: int64

# Hash Code

In [0]:
def BinarySearch(Arr, num, l, r):
  # print("rec")
  index = l
  if l<r:
    mean = l+r//2
    if num==Arr[mean]:
      return mean
    elif num<Arr[mean]:
      return BinarySearch(Arr, num, l, mean)
    else:
      return BinarySearch(Arr, num, mean, r)
  else:
    return index

def fun(Req, arr):
  i=0
  while sum < Req:
    sum += arr[i]
    i+=1
  index = binarySearch(Arr, num, 0, len(Arr))
  return arr

arr = [1,2,3,4,5,6,7,8]
req = 4
print(BinarySearch(arr, req, 0, len(arr)))